import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/authprovider"
// import ToasterProvider from "../lib/providers/ToasterProvider";
// import ToasterProvider from "@/components/lib/providers/ToasterProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <head>
      {/* <style>
        @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap')
       </style> */}
      </head>
      <body className={inter.className}>
      <AuthProvider>
      {/* <ToasterProvider /> */}
        {children}
        </AuthProvider>
        </body>
    </html>
    
  );
}
