import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Footer/page";
import { Header } from "./Header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <style>
@import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap')
</style>
      </head>
      
      <body className={inter.className}>
        <Header/>
        {children}
      <Footer/></body>
    </html>
  );
}
